services:
  - type: web
    name: life-assistant-bot
    runtime: docker
    repo: https://github.com/amir-xyz0/Bot
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: MORNING_MESSAGE_TIME
        value: "07:00"
      - key: NIGHT_MESSAGE_TIME
        value: "23:00"
